#include "LicenseManager.hpp"
#include <iostream>
#include <fstream>
#include <sstream>
#include <chrono>
#include <openssl/evp.h>
#include <openssl/bio.h>
#include <openssl/buffer.h>

namespace sentinel::licensing {

// Master Aryorithm Ed25519 Public Verification Key (Embedded in binary)
// Generated by tools/licensing/keygen.py
static const uint8_t ARYORITHM_MASTER_PUBKEY[32] = {
    0xd7, 0x5a, 0x98, 0x01, 0x82, 0xb1, 0x0a, 0xb7,
    0xd5, 0x4b, 0xfe, 0xd3, 0xc9, 0x64, 0x07, 0x3a,
    0x0e, 0xe1, 0x72, 0xf3, 0xda, 0xa6, 0x23, 0x25,
    0xaf, 0x02, 0x1a, 0x68, 0xf7, 0x07, 0x51, 0x1a
};

// Free Community Tier Default Modules
static const std::unordered_set<std::string> COMMUNITY_MODULES = {
    "01_siem_core", "04_ids_ips", "15_ngfw", "19_swg", "22_dfir"
};

LicenseManager::LicenseManager() {
    // Default fallback state: Community Free Tier
    claims_.tier = LicenseTier::COMMUNITY_FREE;
    claims_.authorized_modules = COMMUNITY_MODULES;
}

std::string LicenseManager::probe_local_hardware_uuid() {
    std::string uuid = "00000000-0000-0000-0000-000000000000";
    std::ifstream dmi("/sys/class/dmi/id/product_uuid");
    if (dmi.is_open()) {
        std::getline(dmi, uuid);
    } else {
        std::ifstream mid("/etc/machine-id");
        if (mid.is_open()) std::getline(mid, uuid);
    }
    // Trim whitespace
    size_t start = uuid.find_first_not_of(" \t\r\n");
    size_t end = uuid.find_last_not_of(" \t\r\n");
    return (start != std::string::npos && end != std::string::npos) ? uuid.substr(start, end - start + 1) : uuid;
}

std::string LicenseManager::generate_hardware_token() {
    std::string hw_uuid = probe_local_hardware_uuid();
    return "ARY-HW-" + hw_uuid;
}

static std::vector<uint8_t> base64_decode(const std::string& input) {
    BIO* b64 = BIO_new(BIO_f_base64());
    BIO_set_flags(b64, BIO_FLAGS_BASE64_NO_NL);
    BIO* bmem = BIO_new_mem_buf(input.data(), static_cast<int>(input.size()));
    bmem = BIO_push(b64, bmem);

    std::vector<uint8_t> output(input.size());
    int decoded_size = BIO_read(bmem, output.data(), static_cast<int>(output.size()));
    BIO_free_all(bmem);

    if (decoded_size > 0) output.resize(decoded_size);
    else output.clear();
    return output;
}

bool LicenseManager::verify_ed25519_signature(const std::string& canonical_json, const std::string& b64_sig) {
    auto sig_bytes = base64_decode(b64_sig);
    if (sig_bytes.size() != 64) {
        return false;
    }

    // Load Ed25519 raw public key using OpenSSL 3 EVP API
    EVP_PKEY* pkey = EVP_PKEY_new_raw_public_key(
        EVP_PKEY_ED25519, nullptr, ARYORITHM_MASTER_PUBKEY, 32
    );
    if (!pkey) return false;

    EVP_MD_CTX* ctx = EVP_MD_CTX_new();
    bool verified = false;

    if (EVP_DigestVerifyInit(ctx, nullptr, nullptr, nullptr, pkey) == 1) {
        if (EVP_DigestVerify(ctx, sig_bytes.data(), sig_bytes.size(),
                             reinterpret_cast<const unsigned char*>(canonical_json.data()),
                             canonical_json.size()) == 1) {
            verified = true;
        }
    }

    EVP_MD_CTX_free(ctx);
    EVP_PKEY_free(pkey);
    return verified;
}

static std::string extract_value(const std::string& json, const std::string& key) {
    size_t k = json.find("\"" + key + "\"");
    if (k == std::string::npos) return "";
    size_t colon = json.find(':', k);
    size_t s = json.find('"', colon + 1);
    size_t e = json.find('"', s + 1);
    if (s != std::string::npos && e != std::string::npos) {
        return json.substr(s + 1, e - s - 1);
    }
    return "";
}

bool LicenseManager::load_and_verify(const std::string& license_file_path) {
    std::lock_guard<std::mutex> lock(mutex_);

    std::ifstream file(license_file_path);
    if (!file.is_open()) {
        std::cout << "[LicenseManager] No license file found at " << license_file_path 
                  << ". Operating in Community Free Tier." << std::endl;
        claims_.tier = LicenseTier::COMMUNITY_FREE;
        claims_.authorized_modules = COMMUNITY_MODULES;
        license_valid_ = false;
        return false;
    }

    std::string content((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());

    // Extract signature
    std::string b64_sig = extract_value(content, "signature");
    if (b64_sig.empty()) {
        std::cerr << "[LicenseManager] Corrupted license: Missing cryptographic signature." << std::endl;
        return false;
    }

    // Extract claims block
    size_t c_start = content.find("\"claims\":");
    size_t obj_start = content.find('{', c_start);
    int brace_count = 0;
    size_t obj_end = std::string::npos;
    for (size_t i = obj_start; i < content.size(); ++i) {
        if (content[i] == '{') brace_count++;
        else if (content[i] == '}') {
            brace_count--;
            if (brace_count == 0) {
                obj_end = i;
                break;
            }
        }
    }

    if (obj_end == std::string::npos) {
        std::cerr << "[LicenseManager] Malformed license envelope." << std::endl;
        return false;
    }

    std::string claims_json = content.substr(obj_start, obj_end - obj_start + 1);

    // Minimize whitespace in claims_json to canonical form for signature verification
    std::string canonical;
    bool in_q = false;
    for (char ch : claims_json) {
        if (ch == '"') in_q = !in_q;
        if (!in_q && (ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r')) continue;
        canonical += ch;
    }

    // Cryptographic signature check
    if (!verify_ed25519_signature(canonical, b64_sig)) {
        std::cerr << "\033[31m[LicenseManager] CRITICAL: Invalid cryptographic signature! "
                  << "License tampering detected. Reverting to Community Tier.\033[0m" << std::endl;
        claims_.tier = LicenseTier::COMMUNITY_FREE;
        claims_.authorized_modules = COMMUNITY_MODULES;
        return false;
    }

    // Expiration check
    std::string exp_str;
    size_t exp_pos = claims_json.find("\"expires_at\":");
    if (exp_pos != std::string::npos) {
        size_t comma = claims_json.find_first_of(",}", exp_pos);
        exp_str = claims_json.substr(exp_pos + 13, comma - exp_pos - 13);
        // Trim
        exp_str.erase(0, exp_str.find_first_not_of(" \t"));
        exp_str.erase(exp_str.find_last_not_of(" \t") + 1);
    }
    uint64_t expires_sec = exp_str.empty() ? 0 : std::stoull(exp_str);
    auto now_sec = std::chrono::duration_cast<std::chrono::seconds>(
        std::chrono::system_clock::now().time_since_epoch()).count();

    if (expires_sec > 0 && static_cast<uint64_t>(now_sec) > expires_sec) {
        std::cerr << "\033[33m[LicenseManager] License expired on timestamp " << expires_sec 
                  << ". Reverting to Community Tier.\033[0m" << std::endl;
        claims_.tier = LicenseTier::COMMUNITY_FREE;
        claims_.authorized_modules = COMMUNITY_MODULES;
        return false;
    }

    // Hardware Lock Check (if bound)
    std::string hw_lock = extract_value(claims_json, "locked_hardware_uuid");
    if (!hw_lock.empty()) {
        std::string local_hw = probe_local_hardware_uuid();
        if (local_hw != hw_lock) {
            std::cerr << "\033[31m[LicenseManager] HARDWARE LOCK VIOLATION: License is bound to [" 
                      << hw_lock << "], but running on [" << local_hw << "]!\033[0m" << std::endl;
            claims_.tier = LicenseTier::COMMUNITY_FREE;
            claims_.authorized_modules = COMMUNITY_MODULES;
            return false;
        }
    }

    // Extract Tier and Customer Name
    claims_.license_id = extract_value(claims_json, "license_id");
    claims_.customer_name = extract_value(claims_json, "customer");
    claims_.locked_hardware_uuid = hw_lock;
    claims_.expires_at_sec = expires_sec;

    std::string tier_str = extract_value(claims_json, "tier");
    if (tier_str == "CRITICAL_OT" || tier_str == "SOVEREIGN_DEFENSE") {
        claims_.tier = LicenseTier::CRITICAL_INFRASTRUCTURE_OT;
    } else {
        claims_.tier = LicenseTier::ENTERPRISE_IT;
    }

    license_valid_ = true;
    std::cout << "\033[32m[LicenseManager] VALID LICENSE VERIFIED: Customer [" << claims_.customer_name 
              << "] | Tier: " << get_tier_name() << "\033[0m" << std::endl;
    return true;
}

bool LicenseManager::is_module_authorized(const std::string& module_name) const {
    std::lock_guard<std::mutex> lock(mutex_);
    if (claims_.tier == LicenseTier::CRITICAL_INFRASTRUCTURE_OT || 
        claims_.tier == LicenseTier::SOVEREIGN_DEFENSE) {
        return true;
    }
    if (claims_.tier == LicenseTier::COMMUNITY_FREE) {
        return COMMUNITY_MODULES.contains(module_name);
    }
    // Enterprise IT authorizes all modules except specialized SCADA and medical
    static const std::unordered_set<std::string> OT_RESTRICTED = {
        "17_iot_sec", "18_cps_sec", "20_fse", "21_side_channel", "26_ddp"
    };
    return !OT_RESTRICTED.contains(module_name);
}

bool LicenseManager::is_plugin_authorized(const std::string& plugin_filename) const {
    std::lock_guard<std::mutex> lock(mutex_);
    if (claims_.tier == LicenseTier::CRITICAL_INFRASTRUCTURE_OT || 
        claims_.tier == LicenseTier::SOVEREIGN_DEFENSE) {
        return true;
    }
    if (claims_.tier == LicenseTier::ENTERPRISE_IT) {
        // Authorize SIEM egress forwarders in Enterprise IT
        return (plugin_filename.find("forwarder") != std::string::npos || 
                plugin_filename.find("kafka") != std::string::npos ||
                plugin_filename.find("syslog") != std::string::npos);
    }
    return false; // Zero industrial plugins in Free Community Tier
}

LicenseTier LicenseManager::get_active_tier() const {
    std::lock_guard<std::mutex> lock(mutex_);
    return claims_.tier;
}

std::string LicenseManager::get_tier_name() const {
    switch (claims_.tier) {
        case LicenseTier::COMMUNITY_FREE: return "Community Free Tier";
        case LicenseTier::ENTERPRISE_IT: return "Enterprise IT Edition";
        case LicenseTier::CRITICAL_INFRASTRUCTURE_OT: return "Critical Infrastructure OT (Full 26 Modules & 30 Plugins)";
        case LicenseTier::SOVEREIGN_DEFENSE: return "Sovereign Defense Enclave";
    }
    return "Unknown";
}

} // namespace sentinel::licensing